steps:
# Build the container images:
  - name: 'gcr.io/cloud-builders/docker'
  - args: ['build', '-t', 'gcr.io/tierheim', '.']
# Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/tierheim']
# Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'tierheim', '--image', 'gcr.io/tierheim', '--region', 'europe-west3', '--platform', 'managed']
images:
  - gcr.io/tierheim
